name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure dnspython v2+ for Eventlet greendns and openpyxl for Excel export
          pip install "dnspython>=2.3.0" openpyxl

      - name: Build with PyInstaller
        run: |
          pyinstaller `
            --hidden-import dns.asyncresolver `
            --collect-submodules dns `
            --noconsole `
            --onefile `
            --name QA_Testing_App `
            --add-data "templates;templates" `
            --add-data "static;static" `
            --collect-all webview `
            --hidden-import flask_socketio `
            --hidden-import socketio `
            --hidden-import engineio `
            --hidden-import eventlet `
            --hidden-import eventlet.green `
            --hidden-import eventlet.green.socket `
            --hidden-import eventlet.support `
            --hidden-import eventlet.support.greenlets `
            --hidden-import eventlet.hubs `
            --hidden-import eventlet.hubs.epolls `
            --hidden-import eventlet.hubs.kqueue `
            --hidden-import eventlet.hubs.selects `
            --hidden-import eventlet.hubs.poll `
            --hidden-import dns `
            --hidden-import dns.asyncquery `
            --hidden-import dns.rdtypes `
            --hidden-import dns.rdatatype `
            --hidden-import dns.exception `
            --hidden-import dns.name `
            --hidden-import dns.message `
            --hidden-import dns.query `
            run_app.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: QA_Testing_App
          path: dist/QA_Testing_App.exe
