name: Build, Test, and Release Windows EXE

on:
  push:
    branches: [main, master]
  workflow_dispatch:
  release:
    types: [created]  # Trigger release job on tag creation

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pytest

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        dir
        dir tests

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests/

    - name: Add comprehensive PyInstaller hook for eventlet and dnspython
    run: |
      echo "hiddenimports = [" > hook-eventlet.py
      echo "    'eventlet.hubs.epolls'," >> hook-eventlet.py
      echo "    'eventlet.hubs.kqueue'," >> hook-eventlet.py
      echo "    'eventlet.hubs.poll'," >> hook-eventlet.py
      echo "    'eventlet.hubs.selects'," >> hook-eventlet.py
      echo "    'dns.asyncquery'," >> hook-eventlet.py
      echo "    'dns.asyncbackend'," >> hook-eventlet.py
      echo "    'dns.asyncresolver'," >> hook-eventlet.py
      echo "    'dns.dnssec'," >> hook-eventlet.py
      echo "    'dns.e164'," >> hook-eventlet.py
      echo "    'dns.rdtypes.ANY'," >> hook-eventlet.py
      echo "    'dns.rdtypes.CH'," >> hook-eventlet.py
      echo "    'dns.rdtypes.IN'," >> hook-eventlet.py
      echo "    'dns.rdtypes.MAIL'," >> hook-eventlet.py
      echo "    'dns.rdtypes.RP'," >> hook-eventlet.py
      echo "    'dns.rdtypes.OTHER'," >> hook-eventlet.py
      echo "    'dns.rdtypes.dnskeybase'," >> hook-eventlet.py
      echo "    'dns.message'," >> hook-eventlet.py
      echo "    'dns.name'," >> hook-eventlet.py
      echo "    'dns.rdatatype'," >> hook-eventlet.py
      echo "    'dns.rdataclass'," >> hook-eventlet.py
      echo "    'dns.exception'," >> hook-eventlet.py
      echo "    'dns.flags'," >> hook-eventlet.py
      echo "    'dns.opcode'," >> hook-eventlet.py
      echo "    'dns.rcode'," >> hook-eventlet.py
      echo "    'dns.rrset'," >> hook-eventlet.py
      echo "    'dns.resolver'" >> hook-eventlet.py
      echo "]" >> hook-eventlet.py





    - name: Build executable with PyInstaller
      run: pyinstaller --additional-hooks-dir=. --name QA_Testing_App --onefile --noconsole --add-data "scan_log.db;." --add-data "templates;templates" --add-data "static;static" app.py

    - name: Smoke test executable
      run: .\dist\QA_Testing_App.exe --help

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: QA_Testing_App
        path: dist/QA_Testing_App.exe

  release:
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download EXE artifact
      uses: actions/download-artifact@v3
      with:
        name: QA_Testing_App
        path: ./artifact

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifact/QA_Testing_App.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
