name: Build, Test, and Release Windows EXE

on:
  push:
    branches: [main, master]
  workflow_dispatch:
  # Trigger release job on tags
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pytest

    - name: Run tests
      run: pytest tests/

    - name: Build exe with PyInstaller
      run: |
        pyinstaller \
          --name QA_Testing_App \
          --onefile \
          --noconsole \
          --add-data "scan_log.db;." \
          --add-data "templates;templates" \
          --add-data "static;static" \
          run_app.py

    - name: Smoke test exe
      run: .\dist\QA_Testing_App.exe --help

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: QA_Testing_App
        path: dist/QA_Testing_App.exe

  release:
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download EXE artifact
      uses: actions/download-artifact@v3
      with:
        name: QA_Testing_App
        path: ./artifact

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifact/QA_Testing_App.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
